.PHONY: all check scratch

all:
	$(MAKE) -C crafted_add_assoc_3var
	$(MAKE) -C crafted_add_comm
	$(MAKE) -C crafted_add_comm_with_id
	$(MAKE) -C crafted_dup
	$(MAKE) -C crafted_equal
	$(MAKE) -C crafted_even
	$(MAKE) -C crafted_mul_assoc_1var_3occ
	$(MAKE) -C crafted_mul_assoc_3var
	$(MAKE) -C crafted_mul_comm
	$(MAKE) -C crafted_mul_distributvity
	$(MAKE) -C generated_add_12sym
	$(MAKE) -C generated_add_27sym
	$(MAKE) -C generated_add_5var_7occ
	$(MAKE) -C generated_leq_1var_1_1occ
	$(MAKE) -C generated_leq_1var_1_2occ
	$(MAKE) -C generated_leq_1var_1_3occ
	$(MAKE) -C generated_leq_1var_5_5occ
	$(MAKE) -C generated_leq_1var_5_9occ

check:
	$(MAKE) -C crafted_add_assoc_3var check
	$(MAKE) -C crafted_add_comm check
	$(MAKE) -C crafted_add_comm_with_id check
	$(MAKE) -C crafted_dup check
	$(MAKE) -C crafted_equal check
	$(MAKE) -C crafted_even check
	$(MAKE) -C crafted_mul_assoc_1var_3occ check
	$(MAKE) -C crafted_mul_assoc_3var check
	$(MAKE) -C crafted_mul_comm check
	$(MAKE) -C crafted_mul_distributvity check
	$(MAKE) -C generated_add_12sym check
	$(MAKE) -C generated_add_27sym check
	$(MAKE) -C generated_add_5var_7occ check
	$(MAKE) -C generated_leq_1var_1_1occ check
	$(MAKE) -C generated_leq_1var_1_2occ check
	$(MAKE) -C generated_leq_1var_1_3occ check
	$(MAKE) -C generated_leq_1var_5_5occ check
	$(MAKE) -C generated_leq_1var_5_9occ check

clean:
	$(MAKE) -C crafted_add_assoc_3var clean
	$(MAKE) -C crafted_add_comm clean
	$(MAKE) -C crafted_add_comm_with_id clean
	$(MAKE) -C crafted_dup clean
	$(MAKE) -C crafted_equal clean
	$(MAKE) -C crafted_even clean
	$(MAKE) -C crafted_mul_assoc_1var_3occ clean
	$(MAKE) -C crafted_mul_assoc_3var clean
	$(MAKE) -C crafted_mul_comm clean
	$(MAKE) -C crafted_mul_distributvity clean
	$(MAKE) -C generated_add_12sym clean
	$(MAKE) -C generated_add_27sym clean
	$(MAKE) -C generated_add_5var_7occ clean
	$(MAKE) -C generated_leq_1var_1_1occ clean
	$(MAKE) -C generated_leq_1var_1_2occ clean
	$(MAKE) -C generated_leq_1var_1_3occ clean
	$(MAKE) -C generated_leq_1var_5_5occ clean
	$(MAKE) -C generated_leq_1var_5_9occ clean

scratch:
	$(MAKE) -C crafted_add_assoc_3var scratch
	$(MAKE) -C crafted_add_comm scratch
	$(MAKE) -C crafted_add_comm_with_id scratch
	$(MAKE) -C crafted_dup scratch
	$(MAKE) -C crafted_equal scratch
	$(MAKE) -C crafted_even scratch
	$(MAKE) -C crafted_mul_assoc_1var_3occ scratch
	$(MAKE) -C crafted_mul_assoc_3var scratch
	$(MAKE) -C crafted_mul_comm scratch
	$(MAKE) -C crafted_mul_distributvity scratch
	$(MAKE) -C generated_add_12sym scratch
	$(MAKE) -C generated_add_27sym scratch
	$(MAKE) -C generated_add_5var_7occ scratch
	$(MAKE) -C generated_leq_1var_1_1occ scratch
	$(MAKE) -C generated_leq_1var_1_2occ scratch
	$(MAKE) -C generated_leq_1var_1_3occ scratch
	$(MAKE) -C generated_leq_1var_5_5occ scratch
	$(MAKE) -C generated_leq_1var_5_9occ scratch
