.PHONY: all check scratch

all:
	$(MAKE) -C crafted_assorted
	$(MAKE) -C crafted_reverse_expressions
	$(MAKE) -C generated_concat_1var_10occ
	$(MAKE) -C generated_concat_1var_3occ
	$(MAKE) -C generated_concat_1var_4occ
	$(MAKE) -C generated_concat_1var_5occ
	$(MAKE) -C generated_concat_1var_6occ
	$(MAKE) -C generated_concat_1var_7occ
	$(MAKE) -C generated_concat_2var_4occ
	$(MAKE) -C generated_concat_3var_3occ
	$(MAKE) -C generated_pref_1var_2_3occ
	$(MAKE) -C generated_pref_1var_5_9occ
	$(MAKE) -C generated_pref_2var_1_2occ

check:
	$(MAKE) -C crafted_assorted check
	$(MAKE) -C crafted_reverse_expressions check
	$(MAKE) -C generated_concat_1var_10occ check
	$(MAKE) -C generated_concat_1var_3occ check
	$(MAKE) -C generated_concat_1var_4occ check
	$(MAKE) -C generated_concat_1var_5occ check
	$(MAKE) -C generated_concat_1var_6occ check
	$(MAKE) -C generated_concat_1var_7occ check
	$(MAKE) -C generated_concat_2var_4occ check
	$(MAKE) -C generated_concat_3var_3occ check
	$(MAKE) -C generated_pref_1var_2_3occ check
	$(MAKE) -C generated_pref_1var_5_9occ check
	$(MAKE) -C generated_pref_2var_1_2occ check

clean:
	$(MAKE) -C crafted_assorted clean
	$(MAKE) -C crafted_reverse_expressions clean
	$(MAKE) -C generated_concat_1var_10occ clean
	$(MAKE) -C generated_concat_1var_3occ clean
	$(MAKE) -C generated_concat_1var_4occ clean
	$(MAKE) -C generated_concat_1var_5occ clean
	$(MAKE) -C generated_concat_1var_6occ clean
	$(MAKE) -C generated_concat_1var_7occ clean
	$(MAKE) -C generated_concat_2var_4occ clean
	$(MAKE) -C generated_concat_3var_3occ clean
	$(MAKE) -C generated_pref_1var_2_3occ clean
	$(MAKE) -C generated_pref_1var_5_9occ clean
	$(MAKE) -C generated_pref_2var_1_2occ clean

scratch:
	$(MAKE) -C crafted_assorted scratch
	$(MAKE) -C crafted_reverse_expressions scratch
	$(MAKE) -C generated_concat_1var_10occ scratch
	$(MAKE) -C generated_concat_1var_3occ scratch
	$(MAKE) -C generated_concat_1var_4occ scratch
	$(MAKE) -C generated_concat_1var_5occ scratch
	$(MAKE) -C generated_concat_1var_6occ scratch
	$(MAKE) -C generated_concat_1var_7occ scratch
	$(MAKE) -C generated_concat_2var_4occ scratch
	$(MAKE) -C generated_concat_3var_3occ scratch
	$(MAKE) -C generated_pref_1var_2_3occ scratch
	$(MAKE) -C generated_pref_1var_5_9occ scratch
	$(MAKE) -C generated_pref_2var_1_2occ scratch
